# Generated by Django 4.2.6 on 2023-10-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('tokens', models.JSONField(default=list)),
                ('temp_tokens', models.JSONField(default=list)),
                ('private_key', models.CharField(max_length=255, null=True)),
                ('public_key', models.CharField(max_length=255, null=True)),
                ('email_verified', models.BooleanField(null=True)),
                ('email_token', models.CharField(max_length=255, null=True)),
                ('password_reset_token', models.CharField(max_length=255, null=True)),
                ('google_drive_enabled', models.BooleanField(null=True)),
                ('google_drive_data', models.JSONField(null=True)),
                ('s3_enabled', models.BooleanField(null=True)),
                ('s3_data', models.JSONField(null=True)),
                ('personal_storage_canceled_date', models.IntegerField(null=True)),
                ('storage_data', models.JSONField(null=True)),
                ('storage_data_personal', models.JSONField(null=True)),
                ('storage_data_google', models.JSONField(null=True)),
                ('active_subscription', models.BooleanField(null=True)),
                ('plan_id', models.CharField(max_length=255, null=True)),
                ('password_last_modified', models.IntegerField(null=True)),
                ('last_subscription_check_time', models.IntegerField(null=True)),
                ('last_subscription_status', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
