# Generated by Django 4.2.6 on 2023-10-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_google_drive_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='owner',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
