# Generated by Django 4.2.6 on 2023-10-23 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
                ('data', models.BinaryField(null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('IV', models.BinaryField(null=True)),
                ('s3ID', models.CharField(max_length=255, null=True)),
                ('personalFile', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('parent', models.CharField(max_length=255, null=True)),
                ('parent_list', models.JSONField(null=True)),
                ('personal_folder', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('parent', models.CharField(max_length=255)),
                ('parent_list', models.JSONField()),
                ('has_thumbnail', models.BooleanField()),
                ('thumbnail_id', models.CharField(max_length=255, null=True)),
                ('original_size', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('is_video', models.BooleanField()),
                ('IV', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField()),
                ('chunk_size', models.PositiveIntegerField(null=True)),
                ('upload_date', models.DateTimeField()),
                ('filename', models.CharField(max_length=255)),
                ('parent', models.CharField(max_length=255)),
                ('parent_list', models.CharField(max_length=255)),
                ('has_thumbnail', models.BooleanField()),
                ('is_video', models.BooleanField()),
                ('thumbnail_id', models.CharField(max_length=255, null=True)),
                ('size', models.PositiveIntegerField()),
                ('IV', models.BinaryField()),
                ('link_type', models.CharField(max_length=255, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('file_path', models.CharField(max_length=255, null=True)),
                ('s3_id', models.CharField(max_length=255, null=True)),
                ('personal_file', models.BooleanField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
