# Generated by Django 4.2.6 on 2023-10-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_remove_thumbnail_personalfile_file_is_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumbnail_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.thumbnail'),
        ),
    ]
