# Generated by Django 4.2.6 on 2023-10-31 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_alter_file_thumbnail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
